name: petudio
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  multiple_images_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_pic_black.jpg
    - assets/logo_word_black.jpg
    - assets/logo_word_blue.jpg
    - assets/pettohuman_word.jpg
    - assets/makingjuniors_word.jpg
    - assets/fourcuts_word.jpg
    - assets/appbar_logo.jpg
    - assets/Logo_of_Petudio_removebg.png
    - assets/11.png
    - assets/22.png
    - assets/33.png
    - assets/44.png
    - assets/result1.jpg
    - assets/result2.jpg
    - assets/result3.jpg    
    - assets/result4.jpg
    - assets/result5.jpg
    - assets/result6.jpg
    - assets/result7.jpg    
    - assets/result8.jpg
    - assets/result9.jpg
    - assets/result10.jpg
    - assets/result11.jpg
    - assets/result12.jpg
    - assets/result13.jpg    
    - assets/result14.jpg
    - assets/result15.jpg
    - assets/result16.jpg
    - assets/result17.jpg    
    - assets/result18.jpg
    - assets/result19.jpg
    - assets/result20.jpg
    - assets/result21.jpg
    - assets/result22.jpg
    - assets/result23.jpg    
    - assets/result24.jpg
    - assets/result25.jpg
    - assets/result26.jpg
    - assets/result27.jpg    
    - assets/result28.jpg
    - assets/result29.jpg
    - assets/result30.jpg
    - assets/result31.jpg
    - assets/result32.jpg
